### PR TITLE
Change splash screen from homebrew to "Licensed by Nintendo"

### PR DESCRIPTION
**Pull request by Zachary-Rude**
This would make it feel more like a real 3DS game. I chose `Licensed` instead of `Nintendo` because then it would be more obvious that it is a 3rd party game.

### CODE REVIEW

**Comment by Zachary-Rude** [comment]
Also, I saw that `-lcurl` was in the `ld` parameters in the Makefile, which was causing the build to fail every time, so I'm trying to fix that as well.

**Comment by tobid7** [comment]
Ah lol yea interesting idea hopefully curl is not required by RenderD7 lol ill take a look on the request later

**Comment by tobid7** [comment]
Ah lol not required yet (lcurl) so i test and merge later

**Comment by tobid7** [comment]
Okay so update: The Licensed is a nice idea
And for the -lcurl you may not have portlibs installed or another error as in my systems it builds sucess but ill let it get removed as it is not required by Flappy Bird or RenderD7

Oh and i could add you to Credits if you want

**Comment by tobid7** [comment]
As the current debug build of the workflow doesnt work caused by RenderD7 :( ive created a temp patched version cause dont want to leak rd7-0.9.5 which fixes the mINI::Parser error by commenting out

**Comment by Zachary-Rude** [comment]
sure! please add me to the credits!

**Comment by Zachary-Rude** [comment]
it still thinks lcurl doesnt exist, im on windows btw

**Comment by tobid7** [comment]
Hmmm may be you didn't run "pacman -Syu 3ds-portlibs" xd but yeah setting up dkp on windows is pain

**Comment by Zachary-Rude** [comment]
i ran that command, but it still doesnt work
and when i remove `-lcurl` from the makefile, it builds successfully, but when i try to launch it on my 3ds, it just crashes after the render d7 splash screen

**Comment by tobid7** [comment]
yeah ik I think you need to grab my latest commit as there is a problem with the config in renderd7 0.9.4 (again) xd may be the latest works (for me) as ive removed the config entirely

**Comment by tobid7** [comment]
hmm still seeing the homebrew logo but it works with the licensed if '-logo "../app/logo.lz11"' gets removed from the Makefile in line 256

**Comment by Zachary-Rude** [comment]
> hmm still seeing the homebrew logo but it works with the licensed if '-logo "../app/logo.lz11"' gets removed from the Makefile in line 256

i'll try that! i'll post an update once i build the cia file on my end! oh, and also, i updated the icon for the game so that it is perfectly square, as opposed to being rounded with a white background

**Comment by Zachary-Rude** [comment]
ok, so i tested it, and removing `-logo "../app/logo.lz11"` does indeed make the licensed logo work! now, i'll push some commits involving the fixed icon and the fixed Makefile!

**Comment by tobid7** [comment]
Before creating a release i'll verify that the patched RenderD7 doesn't make problems... And i recommend to put makerom and bannertool into devkitpro/tools/bin xd

**Comment by Zachary-Rude** [comment]
would you please give me write access to this repo?

**Comment by tobid7** [comment]
Hmmm i could but dont d3stroy the codebase xd

**Comment by tobid7** [comment]
Hmmm i could but dont d3stroy the codebase xd

-Update github should send you an invite mail

**Pull request merged**
